version: "3.7"
services:
  nkm-front:
    restart: always
    build:
      context: .
    image: tojatos/nkm-front
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.nkm-front-stripprefix.stripPrefix.prefixes=/nkm-front"
      - "traefik.http.routers.nkm-front.rule=((Host(`krzysztofruczkowski.pl`) || Host(`www.krzysztofruczkowski.pl`)) && PathPrefix(`/nkm-front/`))"
      - "traefik.http.routers.nkm-front.middlewares=nkm-front-stripprefix"
      - "traefik.http.routers.nkm-front.tls=true"
      - "traefik.http.routers.nkm-front.tls.certresolver=myresolver"
      - "traefik.http.services.nkm-front.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_default"

networks:
  web:
    name: traefik_default
    external: true
