services:
  nkm-front:
    restart: unless-stopped
    build:
      context: .
    image: tojatos/nkm-front
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nkm-front.rule=Host(`nkm.krzysztofruczkowski.pl`)"
      - "traefik.http.routers.nkm-front.tls=true"
      - "traefik.http.routers.nkm-front.tls.certresolver=myresolver"
      - "traefik.http.services.nkm-front.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_default"

networks:
  web:
    name: traefik_default
    external: true
